"""
Invoice PDF Generator
Copyright 2026 ApexDynamics Solutions | Built by Rotimi Ugbana
"""
from fpdf import FPDF
import base64
from datetime import datetime

class ReportBuilder:
    def __init__(self):
        self.company = "ApexDynamics Solutions"
        self.developer = "Rotimi Ugbana"
        self.year = "2026"
    
    def generate_invoice_pdf(self, invoice):
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_fill_color(102, 126, 234)
        pdf.rect(0, 0, 210, 40, 'F')
        pdf.set_font('Arial', 'B', 24)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 20, 'INVOICE', ln=True, align='C')
        pdf.set_font('Arial', '', 12)
        pdf.cell(0, 10, f'#{invoice["invoice_number"]}', ln=True, align='C')
        
        pdf.ln(15)
        pdf.set_text_color(0, 0, 0)
        
        # From/To
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(95, 10, 'From:', ln=0)
        pdf.cell(95, 10, 'To:', ln=1)
        pdf.set_font('Arial', '', 11)
        pdf.cell(95, 7, invoice['from_name'], ln=0)
        pdf.cell(95, 7, invoice['to_name'], ln=1)
        pdf.cell(95, 7, invoice['from_email'], ln=0)
        pdf.cell(95, 7, invoice['to_email'], ln=1)
        
        pdf.ln(10)
        
        # Dates
        pdf.set_font('Arial', 'B', 11)
        pdf.cell(63, 8, f"Date: {invoice['date']}", ln=0)
        pdf.cell(63, 8, f"Due: {invoice['due_date']}", ln=0)
        pdf.cell(63, 8, f"Currency: {invoice['currency']}", ln=1)
        
        pdf.ln(10)
        
        # Items
        pdf.set_fill_color(102, 126, 234)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(80, 8, 'Description', 1, 0, 'C', True)
        pdf.cell(25, 8, 'Qty', 1, 0, 'C', True)
        pdf.cell(30, 8, 'Rate', 1, 0, 'C', True)
        pdf.cell(35, 8, 'Amount', 1, 1, 'C', True)
        
        pdf.set_text_color(0, 0, 0)
        pdf.set_font('Arial', '', 10)
        for item in invoice['items']:
            pdf.cell(80, 8, item.get('description', ''), 1)
            pdf.cell(25, 8, str(item.get('quantity', 1)), 1, 0, 'C')
            pdf.cell(30, 8, f"{float(item.get('rate', 0)):,.2f}", 1, 0, 'R')
            pdf.cell(35, 8, f"{float(item.get('amount', 0)):,.2f}", 1, 1, 'R')
        
        # Totals
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(135, 8, 'Subtotal', 1, 0, 'R')
        pdf.cell(35, 8, f"{invoice['subtotal']:,.2f}", 1, 1, 'R')
        
        if invoice['discount'] > 0:
            pdf.cell(135, 8, f"Discount ({invoice['discount']}%)", 1, 0, 'R')
            pdf.cell(35, 8, f"-{invoice['discount_amount']:,.2f}", 1, 1, 'R')
        
        if invoice['tax_rate'] > 0:
            pdf.cell(135, 8, f"Tax ({invoice['tax_rate']}%)", 1, 0, 'R')
            pdf.cell(35, 8, f"{invoice['tax_amount']:,.2f}", 1, 1, 'R')
        
        pdf.set_fill_color(102, 126, 234)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(135, 10, 'TOTAL', 1, 0, 'R', True)
        pdf.cell(35, 10, f"{invoice['total']:,.2f}", 1, 1, 'R', True)
        
        pdf.set_text_color(0, 0, 0)
        pdf.ln(10)
        
        if invoice.get('notes'):
            pdf.set_font('Arial', 'B', 10)
            pdf.cell(0, 8, 'Notes:', ln=1)
            pdf.set_font('Arial', '', 10)
            pdf.multi_cell(0, 7, invoice['notes'])
        
        pdf.ln(20)
        pdf.set_font('Arial', 'I', 8)
        pdf.cell(0, 10, f'Generated by Invoice Generator Pro | {self.company}', ln=True, align='C')
        pdf.cell(0, 6, f'(c) {self.year} {self.company} | {self.developer}', ln=True, align='C')
        
        pdf_output = pdf.output(dest='S').encode('latin-1')
        return base64.b64encode(pdf_output).decode()